/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pb_23_09_2025_aplicacionproductos_poo;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trcuser
 */
public class NewJFrameListaPreciosEncapsulado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameListaPrecios
     */
    public NewJFrameListaPreciosEncapsulado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerProductos = new javax.swing.JSpinner();
        jButton1Calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonAleatorios = new javax.swing.JButton();
        jButton1Ordenar = new javax.swing.JButton();
        jButton1OrdenAlf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de productos");

        jSpinnerProductos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerProductosStateChanged(evt);
            }
        });

        jButton1Calcular.setText("Calcular");
        jButton1Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CalcularActionPerformed(evt);
            }
        });

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Costo", "%Margen", "%Desc", "%Impuesto", "$utilidad", "$Descuento", "$Impuesto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.setShowGrid(true);
        jScrollPane1.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(8).setPreferredWidth(200);
        }

        jButtonAleatorios.setText("Aleatorios");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jButton1Ordenar.setText("Ordenar Por Precio");
        jButton1Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1OrdenarActionPerformed(evt);
            }
        });

        jButton1OrdenAlf.setText("Ordenar por Alfabeto");

        jLabel2.setText("Encapsulado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(jSpinnerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jButton1Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1OrdenAlf, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1Ordenar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1Calcular)
                                .addComponent(jSpinnerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAleatorios))
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1OrdenAlf)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerProductosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerProductosStateChanged
        // TODO add your handling code here:
        int productos = (int)jSpinnerProductos.getValue();
        DefaultTableModel modelo =(DefaultTableModel) jTableProductos.getModel();
        modelo.setRowCount(productos);
    }//GEN-LAST:event_jSpinnerProductosStateChanged

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        String [] productos = { "mouse", "teclado","tablet","mem USB","audifonos","funda","cable tipo c","pasta termica","alcohol isopropilico","microfibra","extension"};
        int [] impuestos ={0,16,6,16,10,16,22,16,30,16,44};
        
        for(int r=0; r<jTableProductos.getRowCount(); r++){
              jTableProductos.setValueAt(productos[random.nextInt(productos.length)],r, 0);// descrip
            jTableProductos.setValueAt(random.nextInt(50,500), r, 1);//costo
              jTableProductos.setValueAt(random.nextInt(5,20), r, 2);// margen utilidad
             jTableProductos.setValueAt(random.nextInt(0,15), r, 3);// %descuento utilidad
             jTableProductos.setValueAt(impuestos[random.nextInt(11)],r, 4);//% imuesto
        }
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    private void jButton1CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CalcularActionPerformed
        // TODO add your handling code here:
        Producto mouse = new Producto("logitech usb",190,20,5,16);
        jTableProductos.setValueAt(mouse.getDescripcion(),0,0);
        jTableProductos.setValueAt(mouse.getCosto(),0,1);
         jTableProductos.setValueAt(mouse.getMargenUtilidad(),0,2);
          jTableProductos.setValueAt(mouse.getPorcentajeDescuento(),0,3);
           jTableProductos.setValueAt(mouse.getPorcentajeImpuesto(),0,4);
           
           
       jTableProductos.setValueAt(mouse.importeUtilidad(),0,5);
        jTableProductos.setValueAt(mouse.importeImpuesto(),0,7);
        jTableProductos.setValueAt(mouse.importeUtilidad(),0,6);
    }//GEN-LAST:event_jButton1CalcularActionPerformed

    private void jButton1OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1OrdenarActionPerformed
        // TODO add your handling code here:
     Almacen bodega = new Almacen(jTableProductos.getRowCount());
     Producto prod = new Producto();
       for(int r=0; r<jTableProductos.getRowCount(); r++){
     prod.setDescripcion(jTableProductos.getValueAt(r, 0)+"");
     prod.setCosto(Double.parseDouble(jTableProductos.getValueAt(r, 1));
     prod.setMargenUtilidad(jTableProductos.getValueAt(r, 2));
             }
    }//GEN-LAST:event_jButton1OrdenarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListaPreciosEncapsulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListaPreciosEncapsulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListaPreciosEncapsulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListaPreciosEncapsulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameListaPreciosEncapsulado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Calcular;
    private javax.swing.JButton jButton1OrdenAlf;
    private javax.swing.JButton jButton1Ordenar;
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerProductos;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
