/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pb_2025_10_23_preproyecto;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trcuser
 */
public class NewJFrame_PreProyectoArregloParalelo extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame_PreProyecto
     */
    DefaultTableModel modelo;
    public NewJFrame_PreProyectoArregloParalelo() {
        initComponents();
        modelo = (DefaultTableModel)jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jButtonAleatorios = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelSalida = new javax.swing.JLabel();
        jLabelEntrada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTiempoT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de Empleados");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButtonAleatorios.setText("Aleatorios");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Empleado", "Hor", "Min", "Seg", "Hor", "Min", "Seg", "Tiempo Trabajado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        jLabelSalida.setBackground(new java.awt.Color(204, 0, 51));
        jLabelSalida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalida.setText("S A L I D A");
        jLabelSalida.setOpaque(true);

        jLabelEntrada.setBackground(new java.awt.Color(51, 204, 0));
        jLabelEntrada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEntrada.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEntrada.setText("E N T R A D A");
        jLabelEntrada.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Tiempo total");

        jLabelTiempoT.setBackground(new java.awt.Color(153, 153, 255));
        jLabelTiempoT.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabelTiempoT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiempoT.setOpaque(true);

        jButtonOrdenar.setBackground(new java.awt.Color(153, 255, 204));
        jButtonOrdenar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonOrdenar)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTiempoT, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jButtonCalcular)
                                .addComponent(jButtonAleatorios))
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalida)
                            .addComponent(jLabelEntrada, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTiempoT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        modelo.setRowCount((int)jSpinner1.getValue());
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        // TODO add your handling code here:
        Random random= new Random();
        Nombres name= new Nombres();
     for(int r=0; r<modelo.getRowCount();r++){
         modelo.setValueAt(name.nextNombreCompleto(random.nextBoolean()), r, 0);
         modelo.setValueAt(random.nextInt(7,10), r, 1);//horas
         modelo.setValueAt(random.nextInt(60), r, 2);//minutos
         modelo.setValueAt(random.nextInt(60), r, 3);//segundos
         
          modelo.setValueAt(random.nextInt(7,10), r, 4);//horas
         modelo.setValueAt(random.nextInt(60), r, 5);//minutos
         modelo.setValueAt(random.nextInt(60), r, 6);//segundos
         
 
     }
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        Horario ent = new Horario();
        Horario sal = new Horario(13,17,26);
        Horario tiempoTrab;
        Horario tiempoTotal = new Horario();
        
        for(int r=0; r<modelo.getRowCount();r++){
            ent.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));
           ent.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));
           ent.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));
           
           sal.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));
           sal.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));
           sal.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+""));
           
           tiempoTrab=sal.resta(ent);
           tiempoTotal=tiempoTotal.suma(tiempoTrab);
           modelo.setValueAt(tiempoTrab, r, 7);
           jLabelTiempoT.setText(tiempoTotal.toString());
        }
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        // TODO add your handling code here:
        Empleado [] lista = new Empleado[modelo.getRowCount()];
        
        for(int r=0; r<modelo.getRowCount();r++){
            Horario ent= new Horario();
            String  nombres [] = new String[];
            Horario entradas[]= new Horario();
            
            ent.setHoras(Integer.parseInt(modelo.getValueAt(r, 1)+""));
           ent.setMinutos(Integer.parseInt(modelo.getValueAt(r, 2)+""));
           ent.setSegundos(Integer.parseInt(modelo.getValueAt(r, 3)+""));
           Horario sal= new Horario();
           sal.setHoras(Integer.parseInt(modelo.getValueAt(r, 4)+""));
           sal.setMinutos(Integer.parseInt(modelo.getValueAt(r, 5)+""));
           sal.setSegundos(Integer.parseInt(modelo.getValueAt(r, 6)+""));
           Empleado emp= new Empleado(modelo.getValueAt(r, 0)+"",ent,sal);
           nombres[r] modelo.getValueAt(r, 0)+"";
           entradas[r]=ent;
           salidas[r]=sal;
           tiempoTrab[r]=sal.resta(ent);

        }
        for(int i=0; i<tiempoTrab.length-1;i++){
            for(int j=i+1;j<tiempoTrab.length;j++){
                if(tiempoTrab[i].mayor(tiempoTrab[j])){
                    tiempoTrab [i] = tiempoTrab[j];
                    tiempoTrab[i]=tiempoTrab[j];
                    tiempoTrab[j]=aux;
                    
                    aux=entradas[i];
                    entradas[i]=entradas[j];
                    entradas[j]=aux;
                    
                    aux=salidas[i];
                    salidas[i]=salidas[j];
                    salidas[j]=aux;
                    
                    String auxn = nombres[i];
                    nombres[i]=nombres[j];
                    nombres[j]=auxn;
                }
            }
        }
        for(int r=0; r<modelo.getRowCount();r++){
           modelo.setValueAt(nombres[r], r, 0);
           modelo.setValueAt(entradas[r].getHoras(), r, 1);
           modelo.setValueAt(entradas[r].getMinutos(), r, 2);
           modelo.setValueAt(entradas[r].getSegundos(), r, 3);
           
           modelo.setValueAt(salidas[r].getHoras(), r, 4);
           modelo.setValueAt(salidas[r].getMinutos(), r, 5);
           modelo.setValueAt(salidas[r].getSegundos(), r, 6);
           modelo.setValueAt(tiempoTrab[r], r, 7);
        }
         
        
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_PreProyectoArregloParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_PreProyectoArregloParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_PreProyectoArregloParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_PreProyectoArregloParalelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_PreProyectoArregloParalelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEntrada;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelTiempoT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
