/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pb_25130266_proyecto_01;

import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trcuser
 */
public class PB_25130266_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PB_25130266_Frame_01
     */
    public PB_25130266_Frame_01() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCalcularRm = new javax.swing.JButton();
        jButtonOrdenarDesc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelMayor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMenor = new javax.swing.JLabel();
        jButtonAleatorios = new javax.swing.JButton();
        jButtonEjemplo = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonOrdenarAlfa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelSuma = new javax.swing.JLabel();
        jLabelSumaRm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Circuito", "Vb", "Ig", "Rg", "Rm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jButtonCalcularRm.setBackground(new java.awt.Color(255, 153, 204));
        jButtonCalcularRm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonCalcularRm.setText("Calcular Rm");
        jButtonCalcularRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularRmActionPerformed(evt);
            }
        });

        jButtonOrdenarDesc.setBackground(new java.awt.Color(255, 255, 102));
        jButtonOrdenarDesc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOrdenarDesc.setText("Ordenar Desc");
        jButtonOrdenarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarDescActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("El Mayor :");

        jLabelMayor.setBackground(new java.awt.Color(255, 204, 204));
        jLabelMayor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMayor.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("El Menor:");

        jLabelMenor.setBackground(new java.awt.Color(204, 204, 255));
        jLabelMenor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelMenor.setOpaque(true);

        jButtonAleatorios.setBackground(new java.awt.Color(153, 255, 204));
        jButtonAleatorios.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonAleatorios.setText("Generar Aleatorios");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jButtonEjemplo.setBackground(new java.awt.Color(153, 153, 255));
        jButtonEjemplo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonEjemplo.setText("Generar Ejemplo");
        jButtonEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjemploActionPerformed(evt);
            }
        });

        jButtonBorrar.setBackground(new java.awt.Color(255, 153, 102));
        jButtonBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonOrdenarAlfa.setBackground(new java.awt.Color(153, 255, 153));
        jButtonOrdenarAlfa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonOrdenarAlfa.setText("Ordenar  Alfabeti");
        jButtonOrdenarAlfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarAlfaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_25130266_proyecto_01/PB_25130266_Asignacion_01.png"))); // NOI18N

        jLabelSuma.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSuma.setText("Suma Rm");

        jLabelSumaRm.setBackground(new java.awt.Color(102, 255, 102));
        jLabelSumaRm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSumaRm.setOpaque(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_25130266_proyecto_01/Ejemplo.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pb_25130266_proyecto_01/Formula.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonOrdenarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonOrdenarAlfa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCalcularRm))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabelSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSumaRm, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSumaRm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSuma, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabelMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButtonEjemplo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAleatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCalcularRm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonOrdenarDesc)
                    .addComponent(jButtonOrdenarAlfa))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        DecimalFormat formato = new DecimalFormat("###,##0.00");

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        String [] identificadores = {"X-5","G-89","H-90","W-76","Q-43","F-8","Y-2","Z-32","C-45","A-56"};
        for(int r=0; r< jTable1.getRowCount();r++){
            jTable1.setValueAt(identificadores[random.nextInt(identificadores.length)],r,0);
            jTable1.setValueAt(random.nextDouble(20,500), r, 1); // Vb
            jTable1.setValueAt(random.nextDouble(1,10), r, 2);// Ig
            jTable1.setValueAt(random.nextDouble(1,20), r, 3); // Rg
        }
        
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    private void jButtonEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjemploActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    
    for (int i = 0; i < modelo.getRowCount(); i++) {
        for (int j = 0; j < modelo.getColumnCount(); j++) {
            modelo.setValueAt("", i, j); 
        }
    }
        jTable1.setValueAt("X -18", 0, 0);
        jTable1.setValueAt(480, 0, 1);
        jTable1.setValueAt(6, 0, 2);
        jTable1.setValueAt(5, 0, 3);
        
         jTable1.setValueAt("L- 25", 1, 0);
        jTable1.setValueAt(312, 1, 1);
        jTable1.setValueAt(7, 1, 2);
        jTable1.setValueAt(8, 1, 3);
        
         jTable1.setValueAt("A- 96", 2, 0);
        jTable1.setValueAt(187, 2, 1);
        jTable1.setValueAt(2, 2, 2);
        jTable1.setValueAt(6, 2, 3);
        
         jTable1.setValueAt("M- 74", 3, 0);
        jTable1.setValueAt(240, 3, 1);
        jTable1.setValueAt(4, 3, 2);
        jTable1.setValueAt(3, 3, 3);
        
         jTable1.setValueAt("G-39", 4, 0);
        jTable1.setValueAt(36, 4, 1);
        jTable1.setValueAt(2, 4, 2);
        jTable1.setValueAt(15, 4, 3);
        
    }//GEN-LAST:event_jButtonEjemploActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    
    for (int i = 0; i < modelo.getRowCount(); i++) {
        for (int j = 0; j < modelo.getColumnCount(); j++) {
            modelo.setValueAt("", i, j); 
        }
    }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonCalcularRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularRmActionPerformed
         AlmacenCircuitos tabla = new AlmacenCircuitos(jTable1);
        tabla.mostrar(jTable1,jLabelSumaRm); 
           tabla.mayor();
        tabla.menor();
          jLabelMayor.setText(tabla.mayor().getIdentificador()+"");
        jLabelMenor.setText(tabla.menor().getIdentificador()+"");
    }//GEN-LAST:event_jButtonCalcularRmActionPerformed

    private void jButtonOrdenarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarDescActionPerformed
            // TODO add your handling code here:
          AlmacenCircuitos tabla = new AlmacenCircuitos(jTable1);             
         tabla.ordenarRm();
             tabla.mostrar(jTable1, jLabelSumaRm); 
         tabla.mayor();
        tabla.menor();
        jLabelMayor.setText(tabla.mayor().getIdentificador()+"");
        jLabelMenor.setText(tabla.menor().getIdentificador()+"");

    }//GEN-LAST:event_jButtonOrdenarDescActionPerformed

    private void jButtonOrdenarAlfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarAlfaActionPerformed
        // TODO add your handling code here:
        AlmacenCircuitos tabla = new AlmacenCircuitos(jTable1);
        tabla.ordenarAlfab();
        tabla.mostrar(jTable1,jLabelSumaRm);
           tabla.mayor();
        tabla.menor();
          jLabelMayor.setText(tabla.mayor().getIdentificador()+"");
        jLabelMenor.setText(tabla.menor().getIdentificador()+"");
         
    }//GEN-LAST:event_jButtonOrdenarAlfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PB_25130266_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PB_25130266_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PB_25130266_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PB_25130266_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PB_25130266_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCalcularRm;
    private javax.swing.JButton jButtonEjemplo;
    private javax.swing.JButton jButtonOrdenarAlfa;
    private javax.swing.JButton jButtonOrdenarDesc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelMayor;
    private javax.swing.JLabel jLabelMenor;
    private javax.swing.JLabel jLabelSuma;
    private javax.swing.JLabel jLabelSumaRm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
