/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pb_2025_10_15_aplicacionmatriz;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pb_2025_10_15_aplicacionmatriz.Matriz;

/**
 *
 * @author trcuser
 */
public class JFrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCalculadora
     */
         DefaultTableModel modeloA,modeloB,modeloC ;

                      Matriz A,B,C;

    public JFrameCalculadora() {
        initComponents();
        modeloA = (DefaultTableModel) jTableMatrizA.getModel();
        modeloB = (DefaultTableModel) jTableMatrizB.getModel();
         modeloC = (DefaultTableModel) jTableMatrizC.getModel();

         
         //nulas
        
    }

    public void crearMatrizA(){
                A = new Matriz(modeloA.getRowCount(),modeloA.getColumnCount());
                  for(int r=0; r<A.getNumeroRenglones();r++){
            for(int c=0;c<A.getNumeroColumnas();c++){
                A.setValor(Double.parseDouble(modeloA.getValueAt(r, c)+""),r, c);
            }
        }
    }
    
    public void crearMatrizB(){
                B = new Matriz(modeloA.getRowCount(),modeloA.getColumnCount());
                 for(int r=0; r<B.getNumeroRenglones();r++){
            for(int c=0;c<B.getNumeroColumnas();c++){
                B.setValor(Double.parseDouble(modeloB.getValueAt(r, c)+""),r, c);
            }
        }
    }
    public void mostrarMatrizC(){
          if(C==null)
              JOptionPane.showMessageDialog(rootPane, "Operacion no valida");
          else{
            jLabelRC.setText(C.getNumeroRenglones()+"");
            jLabelCC.setText(C.getNumeroColumnas()+"");
            
            modeloC.setRowCount(C.getNumeroRenglones());
            modeloC.setColumnCount(C.getNumeroColumnas());
            
            for(int r=0; r<C.getNumeroRenglones();r++){
             for(int c=0; c<C.getNumeroColumnas();c++){
                 modeloC.setValueAt(C.GetValor(r, c), r, c);
             }   
            }
          }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinRA = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSpinCA = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatrizA = new javax.swing.JTable();
        jSpinRB = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinCB = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMatrizB = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMatrizC = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelRC = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jButtonMas = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonMultipli = new javax.swing.JButton();
        jTextEscalar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonAleatorios = new javax.swing.JButton();
        jCheckSincronizar = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButtonCopiarRe = new javax.swing.JButton();
        jRadioButtonMatrizA = new javax.swing.JRadioButton();
        jRadioButtonMatrizB = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabelEjemploInver = new javax.swing.JLabel();
        jButtonTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSpinRA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinRAStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("R");

        jSpinCA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCAStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("C");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Matriz A");

        jTableMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMatrizA.setRowHeight(26);
        jTableMatrizA.setShowGrid(true);
        jScrollPane1.setViewportView(jTableMatrizA);

        jSpinRB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinRBStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("R");

        jSpinCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinCBStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("C");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Matriz B");

        jTableMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMatrizB.setRowHeight(26);
        jTableMatrizB.setShowGrid(true);
        jScrollPane2.setViewportView(jTableMatrizB);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Matriz C");

        jTableMatrizC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableMatrizC.setRowHeight(26);
        jTableMatrizC.setShowGrid(true);
        jScrollPane3.setViewportView(jTableMatrizC);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("C");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("R");

        jLabelRC.setBackground(new java.awt.Color(153, 255, 255));
        jLabelRC.setForeground(new java.awt.Color(51, 51, 51));
        jLabelRC.setOpaque(true);

        jLabelCC.setBackground(new java.awt.Color(153, 255, 255));
        jLabelCC.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCC.setOpaque(true);

        jButtonMas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMas.setText("+");
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });

        jButtonMenos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMenos.setText("-");
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });

        jButtonMultipli.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonMultipli.setText("X");
        jButtonMultipli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipliActionPerformed(evt);
            }
        });

        jTextEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEscalarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Escalar");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("=");

        jButtonAleatorios.setText("Aleatorios");
        jButtonAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatoriosActionPerformed(evt);
            }
        });

        jCheckSincronizar.setText("Sincronizar");

        jLabel10.setBackground(new java.awt.Color(102, 255, 153));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ejemplo");
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        jButtonCopiarRe.setBackground(new java.awt.Color(51, 51, 255));
        jButtonCopiarRe.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonCopiarRe.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCopiarRe.setText("Copiar Resultado a");
        jButtonCopiarRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopiarReActionPerformed(evt);
            }
        });

        jRadioButtonMatrizA.setText("Matriz A");

        jRadioButtonMatrizB.setText("Matriz B");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Vaciar Matrices");

        jLabelEjemploInver.setText("Ejemplo Inversa");
        jLabelEjemploInver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelEjemploInverMouseEntered(evt);
            }
        });

        jButtonTrans.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonTrans.setText("Transpuesta");
        jButtonTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinRA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinCA, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckSincronizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinRB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinCB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCopiarRe, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEjemploInver)
                                .addGap(125, 125, 125))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonMultipli, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1)
                                            .addComponent(jButtonTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonMatrizA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonMatrizB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(196, 196, 196))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelCC, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                                    .addComponent(jLabelRC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(236, 236, 236))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jSpinCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jSpinRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(jButtonTrans)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton1)
                                            .addGap(31, 31, 31)
                                            .addComponent(jButtonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButtonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jButtonMultipli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextEscalar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabelEjemploInver))))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButtonAleatorios)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckSincronizar))))
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCopiarRe)
                            .addComponent(jRadioButtonMatrizA)
                            .addComponent(jRadioButtonMatrizB))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinRAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinRAStateChanged
        // TODO add your handling code here:
        int renglones = (int)jSpinRA.getValue();
        modeloA.setRowCount(renglones);
        if(jCheckSincronizar.isSelected()){
            jSpinRB.setValue(renglones);
        }
    }//GEN-LAST:event_jSpinRAStateChanged

    private void jSpinCAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCAStateChanged
        // TODO add your handling code here:
        int columnas=(int)jSpinCA.getValue();
        modeloA.setColumnCount(columnas);
        if(jCheckSincronizar.isSelected()){
            jSpinCB.setValue(columnas);
        }
            
    }//GEN-LAST:event_jSpinCAStateChanged

    private void jSpinRBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinRBStateChanged
        // TODO add your handling code here:
           int renglones = (int)jSpinRB.getValue();
        modeloB.setRowCount(renglones);
        if(jCheckSincronizar.isSelected()){
            jSpinRA.setValue(renglones);
        }
    }//GEN-LAST:event_jSpinRBStateChanged

    private void jSpinCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinCBStateChanged
        // TODO add your handling code here:
        int columnas=(int)jSpinCB.getValue();
        modeloB.setColumnCount(columnas);
        if(jCheckSincronizar.isSelected()){
            jSpinCA.setValue(columnas);
        }
    }//GEN-LAST:event_jSpinCBStateChanged

    private void jButtonAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatoriosActionPerformed
        // TODO add your handling code here:
        Random random = new Random();
        for(int r=0; r<modeloA.getRowCount(); r++){
            for(int c=0;c<modeloA.getColumnCount();c++){
                modeloA.setValueAt(random.nextInt(10), r, c);
            }
        }
        for(int r=0; r<modeloB.getRowCount(); r++){
            for(int c=0;c<modeloB.getColumnCount();c++){
                modeloB.setValueAt(random.nextInt(10), r, c);
            }
        }
        
    }//GEN-LAST:event_jButtonAleatoriosActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        // TODO add your handling code here:
        crearMatrizA();
      
        crearMatrizB();
        
          C=A.Sumar(B);
         
         mostrarMatrizC();

          
    }//GEN-LAST:event_jButtonMasActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        // TODO add your handling code here:
         crearMatrizA();
      
        crearMatrizB();
        
          C=A.Restar(B);
         
         mostrarMatrizC();

    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonMultipliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipliActionPerformed
        // TODO add your handling code here:
        crearMatrizA();
          if(jTextEscalar.getText().equals("")){
              //multiplicacion de matrices
              crearMatrizB();
              C=A.MultiplicarMatriz(B);
          }
          else{
              //multiplicacion por escalar
              C=A.MultiplicarEscalar(Double.parseDouble(jTextEscalar.getText()));
          }
        mostrarMatrizC();
    }//GEN-LAST:event_jButtonMultipliActionPerformed

    private void jTextEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEscalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEscalarActionPerformed

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jCheckSincronizar.setSelected(false);
        
        jSpinRA.setValue(3);
        jSpinCA.setValue(2);
        
        jSpinRB.setValue(2);
        jSpinCB.setValue(3);
        
        modeloA.setValueAt(1, 0, 0);
        modeloA.setValueAt(2, 0, 1);
        modeloA.setValueAt(3, 1, 0);
        modeloA.setValueAt(4, 1, 1);
        modeloA.setValueAt(5, 2, 0);
        modeloA.setValueAt(6, 2, 1);
        
        modeloB.setValueAt(1, 0, 0);
        modeloB.setValueAt(2, 0, 1);
        modeloB.setValueAt(3, 0, 2);
        modeloB.setValueAt(3, 0, 0);
        modeloB.setValueAt(4, 1, 1);
        modeloB.setValueAt(5, 2, 2);
        
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jButtonCopiarReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopiarReActionPerformed
        // TODO add your handling code here:jCheck
        if(jRadioButtonMatrizA.isSelected()){
            jSpinRA.setValue(modeloC.getRowCount());
           jSpinCA.setValue(modeloC.getColumnCount());
           
           for(int r=0; r<modeloC.getRowCount();r++){
               for(int c=0; c<modeloC.getColumnCount();c++){
                   modeloA.setValueAt(modeloC.getValueAt(r, c), r, c);
               }
           }
        }
        else{
             if(jRadioButtonMatrizB.isSelected()){
            jSpinRB.setValue(modeloC.getRowCount());
           jSpinCB.setValue(modeloC.getColumnCount());
           
           for(int r=0; r<modeloC.getRowCount();r++){
               for(int c=0; c<modeloC.getColumnCount();c++){
                   modeloB.setValueAt(modeloC.getValueAt(r, c), r, c);
               }
           }
        }
        }
    }//GEN-LAST:event_jButtonCopiarReActionPerformed

    private void jLabelEjemploInverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEjemploInverMouseEntered
        // TODO add your handling code here:
        jCheckSincronizar.setSelected(false);
        double[][] f ={ {2,1,1},{3,4,-2},{0,-3,4} };
        
        double[][] u ={ {-10,7,6},{12,-8,-7},{9,-6,-5} };
        
        C=new Matriz(f);
        mostrarMatrizC();
        jRadioButtonMatrizA.setSelected(true);
       jButtonCopiarRe.doClick();
       
        C=new Matriz(u);
        mostrarMatrizC();
        jRadioButtonMatrizB.setSelected(true);
       jButtonCopiarRe.doClick();
    }//GEN-LAST:event_jLabelEjemploInverMouseEntered

    private void jButtonTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonMatrizA.isSelected()){
            crearMatrizA();
            C=A.transpuesta();
            mostrarMatrizC();
        }
        else{
            crearMatrizB();
            C=B.transpuesta();
            mostrarMatrizC();
        }
    }//GEN-LAST:event_jButtonTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAleatorios;
    private javax.swing.JButton jButtonCopiarRe;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMultipli;
    private javax.swing.JButton jButtonTrans;
    private javax.swing.JCheckBox jCheckSincronizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelEjemploInver;
    private javax.swing.JLabel jLabelRC;
    private javax.swing.JRadioButton jRadioButtonMatrizA;
    private javax.swing.JRadioButton jRadioButtonMatrizB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinCA;
    private javax.swing.JSpinner jSpinCB;
    private javax.swing.JSpinner jSpinRA;
    private javax.swing.JSpinner jSpinRB;
    private javax.swing.JTable jTableMatrizA;
    private javax.swing.JTable jTableMatrizB;
    private javax.swing.JTable jTableMatrizC;
    private javax.swing.JTextField jTextEscalar;
    // End of variables declaration//GEN-END:variables
}
